version: '3.8'
services:
  app:
    build: .
    image: your-image-name:latest  # Имя образа и тег
    container_name: your-container-name  # Имя контейнера
    restart: always
    volumes:
      - .:/app
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - POLL_INTERVAL=300